version: '3.9'

services:

    backend:
        container_name: backend_container
        build: ./backend/
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - ./backend/.env
        volumes:
            - ./backend/server:/server

    frontend:
        container_name: frontend_container
        build: ./frontend/
        restart: always
        ports:
            - "8080:8080"
        env_file:
            - ./frontend/.env
        volumes:
            - ./frontend/client:/client

    db:
        container_name: pg_container
        build: ./postgres/
        restart: always
        env_file:
            - ./postgres/.env
        ports:
            - "5432:5432"

    pgadmin:
        container_name: pgadmin4_container
        build: ./pgadmin/
        restart: always
        env_file:
            - ./pgadmin/.env
        ports:
            - "5050:80"
