version: '3.9'

services:

  backend:
    container_name: backend_container
    build: ./backend/
    restart: always
    environment:
      DB_NAME: transcendence
      DB_HOST: pg_container
      DB_PASSWORD: root
      DB_USERNAME: root
      DB_PORT: 5432
    ports:
      - "3000:3000"
    volumes:
      - ./backend/server:/server

  frontend:
    container_name: frontend_container
    build: ./frontend/
    restart: always
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/client:/client

  db:
    container_name: pg_container
    build: ./postgres/
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: transcendence
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    build: ./pgadmin/
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
